#############################################################################
# Makefile for building: wowview
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Jan 26 18:15:25 2012
# Project:  WoWView.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile WoWView.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_USE_QSTRINGBUILDER -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iinclude
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib64/qt4
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/X11R6/lib -lQtNetwork -lQtCore -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/charData.cpp \
		src/mainWindow.cpp \
		src/newChar_dialog.cpp \
		lib/qt-json/json.cpp moc_charData.cpp \
		moc_newChar_dialog.cpp \
		moc_mainWindow.cpp
OBJECTS       = main.o \
		charData.o \
		mainWindow.o \
		newChar_dialog.o \
		json.o \
		moc_charData.o \
		moc_newChar_dialog.o \
		moc_mainWindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		WoWView.pro
QMAKE_TARGET  = wowview
DESTDIR       = 
TARGET        = wowview

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): include/ui_mainWindow.h include/ui_newChar_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: WoWView.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtNetwork.prl
	$(QMAKE) -o Makefile WoWView.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile WoWView.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/wowview1.0.0 || $(MKDIR) .tmp/wowview1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/wowview1.0.0/ && $(COPY_FILE) --parents include/charData.h include/newChar_dialog.h include/mainWindow.h lib/qt-json/json.h .tmp/wowview1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/charData.cpp src/mainWindow.cpp src/newChar_dialog.cpp lib/qt-json/json.cpp .tmp/wowview1.0.0/ && $(COPY_FILE) --parents include/mainWindow.ui include/newChar_dialog.ui .tmp/wowview1.0.0/ && (cd `dirname .tmp/wowview1.0.0` && $(TAR) wowview1.0.0.tar wowview1.0.0 && $(COMPRESS) wowview1.0.0.tar) && $(MOVE) `dirname .tmp/wowview1.0.0`/wowview1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/wowview1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_charData.cpp moc_newChar_dialog.cpp moc_mainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_charData.cpp moc_newChar_dialog.cpp moc_mainWindow.cpp
moc_charData.cpp: include/charData.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/charData.h -o moc_charData.cpp

moc_newChar_dialog.cpp: include/ui_newChar_dialog.h \
		include/newChar_dialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/newChar_dialog.h -o moc_newChar_dialog.cpp

moc_mainWindow.cpp: include/ui_mainWindow.h \
		include/charData.h \
		include/mainWindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) include/mainWindow.h -o moc_mainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: include/ui_mainWindow.h include/ui_newChar_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) include/ui_mainWindow.h include/ui_newChar_dialog.h
include/ui_mainWindow.h: include/mainWindow.ui
	/usr/bin/uic include/mainWindow.ui -o include/ui_mainWindow.h

include/ui_newChar_dialog.h: include/newChar_dialog.ui
	/usr/bin/uic include/newChar_dialog.ui -o include/ui_newChar_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp include/charData.h \
		include/mainWindow.h \
		include/ui_mainWindow.h \
		include/newChar_dialog.h \
		include/ui_newChar_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

charData.o: src/charData.cpp include/charData.h \
		lib/qt-json/json.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o charData.o src/charData.cpp

mainWindow.o: src/mainWindow.cpp include/mainWindow.h \
		include/ui_mainWindow.h \
		include/charData.h \
		include/newChar_dialog.h \
		include/ui_newChar_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o src/mainWindow.cpp

newChar_dialog.o: src/newChar_dialog.cpp include/mainWindow.h \
		include/ui_mainWindow.h \
		include/charData.h \
		include/newChar_dialog.h \
		include/ui_newChar_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newChar_dialog.o src/newChar_dialog.cpp

json.o: lib/qt-json/json.cpp lib/qt-json/json.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o json.o lib/qt-json/json.cpp

moc_charData.o: moc_charData.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_charData.o moc_charData.cpp

moc_newChar_dialog.o: moc_newChar_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newChar_dialog.o moc_newChar_dialog.cpp

moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindow.o moc_mainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

